

GET https://ppampflzn7.execute-api.us-east-2.amazonaws.com/prod/vacations
###

POST https://ppampflzn7.execute-api.us-east-2.amazonaws.com/prod/vacations
content-type: application/json

{
    "location": "London",
    "name":"London item"
    
}
###

GET https://ppampflzn7.execute-api.us-east-2.amazonaws.com/prod/vacations?id=adb35f9c-5d1d-4d4b-804a-5579e12a5296
###

DELETE https://ppampflzn7.execute-api.us-east-2.amazonaws.com/prod/vacations?id=adb35f9c-5d1d-4d4b-804a-5579e12a5296
###

PUT https://ppampflzn7.execute-api.us-east-2.amazonaws.com/prod/vacations?id=adb35f9c-5d1d-4d4b-804a-5579e12a5296
content-type: application/json

{
    "location": "London Updated"
}
###